node{
stage (‘SCM Checkout’){
      //checkout code from repo
      checkout scm
  git“https://github.com/raghulkumar91805/kube-test/”
}
stage(‘Build’){
dir(“src”) {
sh “mvn clean install”
}
dir(“comtest/target”) {
sh “java -jar sele-kub-0.0.1-SNAPSHOT.jar”
}
}
}
