node {
stage (‘SCM checkout’){
git “https://github.com/raghulkumar9180/kube-test/tree/master/sele-kub”
}
stage (‘Build’){
dir(“src”) {
sh “mvn clean install”
}
dir(“comtest/target”) {
sh “java -jar sele-kub-0.0.1-SNAPSHOT.jar”
}
}
}
